spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/major_selection
    username: major_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

recommendation:
  file-path: /home/hosseini/modemkomak_scraper/clean_results.json
jwt:
  secret: b1e72398cfa1471289a7283d5827bc7ab1e72398cfa1471289a7283d5827bc7a
  expiration: 86400000 # 24h in milliseconds

